-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 18:56:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema recetasowc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recetasowc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recetasowc` DEFAULT CHARACTER SET utf8 ;
USE `recetasowc` ;

-- -----------------------------------------------------
-- Table `recetasowc`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasowc`.`ingredientes` (
  `ing_id` INT NOT NULL AUTO_INCREMENT,
  `ing_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ing_id`),
  UNIQUE INDEX `ing_nombre_UNIQUE` (`ing_nombre` ASC) VISIBLE) 
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasowc`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasowc`.`administradores` (
  `adm_rut` VARCHAR(12) NOT NULL,
  `adm_nombre` VARCHAR(45) NOT NULL,
  `adm_apellido` VARCHAR(45) NULL,
  `adm_correo` VARCHAR(45) NULL,
  `adm_password` VARCHAR(20) NOT NULL,
  `adm_nivel_permiso` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`adm_rut`),
  UNIQUE INDEX `adm_rut_UNIQUE` (`adm_rut` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasowc`.`recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasowc`.`recetas` (
  `rec_id` INT NOT NULL AUTO_INCREMENT,
  `rec_imageurl` VARCHAR(255) NULL,
  `rec_nombre` VARCHAR(45) NOT NULL,
  `rec_descripcion` VARCHAR(45) NOT NULL,
  `rec_porciones` INT NULL,
  `rec_duracion` INT NULL,
  `rec_preparacion` TEXT NOT NULL,
  `adm_rut` VARCHAR(12) NULL,
  `rec_fecha_creacion` TIMESTAMP NULL,
  `rec_ultima_modif` TIMESTAMP NULL,
  PRIMARY KEY (`rec_id`),
  UNIQUE INDEX `rec_nombre_UNIQUE` (`rec_nombre` ASC) VISIBLE,
  INDEX `adm_rut_idx` (`adm_rut` ASC) VISIBLE,
  CONSTRAINT `adm_rut`
    FOREIGN KEY (`adm_rut`)
    REFERENCES `recetasowc`.`administradores` (`adm_rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recetasowc`.`ingredientes_receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recetasowc`.`ingredientes_receta` (
  `rec_id` INT NOT NULL,
  `ing_id` INT NOT NULL,
  `ing_cantidad` VARCHAR(45) NOT NULL,
  INDEX `rec_id_idx` (`rec_id` ASC) VISIBLE,
  INDEX `ing_id_idx` (`ing_id` ASC) VISIBLE,
  CONSTRAINT `rec_id`
    FOREIGN KEY (`rec_id`)
    REFERENCES `recetasowc`.`recetas` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ing_id`
    FOREIGN KEY (`ing_id`)
    REFERENCES `recetasowc`.`ingredientes` (`ing_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
